-- Phase 11 — lease_lifecycle_documents table
--
-- Tracks the three new document types generated by Phase 11:
--   renewal_lease         — new lease row created for a renewal term
--   termination_notice    — landlord/tenant termination notice
--   rent_increase_letter  — notice of rent increase
--   m2m_conversion        — month-to-month conversion document
--
-- Every row has a SHA-256 hash of the PDF for integrity, the effective
-- date of the notice, and the number of state-law notice days that were
-- required/applied.  Delivery tracking columns let admin confirm the
-- tenant was actually served.
--
-- Idempotent: all DDL uses IF NOT EXISTS guards.
-- RLS: admins see all; tenant sees rows where lease_id links to their app.

CREATE TABLE IF NOT EXISTS public.lease_lifecycle_documents (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lease_id                  UUID NOT NULL REFERENCES public.leases(id) ON DELETE CASCADE,
  doc_type                  TEXT NOT NULL CHECK (doc_type IN (
                              'renewal_lease',
                              'termination_notice',
                              'rent_increase_letter',
                              'm2m_conversion'
                            )),
  notice_type               TEXT,
  effective_date            DATE NOT NULL,
  generated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  generated_by              TEXT,
  state_code                CHAR(2) NOT NULL,
  state_notice_days_required INT,
  storage_path              TEXT,
  sha256                    TEXT,
  metadata                  JSONB,
  delivered_at              TIMESTAMPTZ,
  delivery_method           TEXT
);

ALTER TABLE public.lease_lifecycle_documents ENABLE ROW LEVEL SECURITY;

-- Admin: full access
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'lease_lifecycle_documents'
      AND policyname = 'admin_all_lifecycle_docs'
  ) THEN
    CREATE POLICY admin_all_lifecycle_docs
      ON public.lease_lifecycle_documents
      FOR ALL
      USING (
        EXISTS (
          SELECT 1 FROM public.admin_roles ar
          WHERE ar.user_id = auth.uid()
        )
      );
  END IF;
END $$;

-- Tenant: read own lease lifecycle documents
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'lease_lifecycle_documents'
      AND policyname = 'tenant_read_own_lifecycle_docs'
  ) THEN
    CREATE POLICY tenant_read_own_lifecycle_docs
      ON public.lease_lifecycle_documents
      FOR SELECT
      USING (
        EXISTS (
          SELECT 1
          FROM public.leases l
          JOIN public.applications a ON a.app_id = l.app_id
          WHERE l.id = lease_lifecycle_documents.lease_id
            AND a.email = (
              SELECT email FROM auth.users WHERE id = auth.uid()
            )
        )
      );
  END IF;
END $$;

GRANT SELECT ON public.lease_lifecycle_documents TO authenticated;
GRANT INSERT, UPDATE ON public.lease_lifecycle_documents TO service_role;

-- Index for fast lookups by lease
CREATE INDEX IF NOT EXISTS lease_lifecycle_documents_lease_id_idx
  ON public.lease_lifecycle_documents (lease_id);
CREATE INDEX IF NOT EXISTS lease_lifecycle_documents_doc_type_idx
  ON public.lease_lifecycle_documents (doc_type);
CREATE INDEX IF NOT EXISTS lease_lifecycle_documents_effective_date_idx
  ON public.lease_lifecycle_documents (effective_date);

-- Renewal tracking column on leases (set when a renewal lease is created)
ALTER TABLE public.leases
  ADD COLUMN IF NOT EXISTS parent_lease_id UUID REFERENCES public.leases(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS leases_parent_lease_id_idx
  ON public.leases (parent_lease_id);

COMMENT ON TABLE public.lease_lifecycle_documents IS
  'Phase 11: one row per generated lifecycle document (renewal, termination notice, rent increase letter).';

COMMENT ON COLUMN public.leases.parent_lease_id IS
  'Phase 11: FK to the prior lease this row renews/replaces. NULL for original leases.';
