CREATE TABLE public.property_tour_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id TEXT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  invitee_name TEXT,
  invitee_email TEXT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  created_by UUID NOT NULL REFERENCES auth.users(id),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + INTERVAL '30 days'),
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.property_tour_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invite_id UUID NOT NULL UNIQUE REFERENCES public.property_tour_invites(id) ON DELETE CASCADE,
  property_id TEXT NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  guest_name TEXT NOT NULL,
  guest_email TEXT NOT NULL,
  guest_phone TEXT,
  requested_times JSONB NOT NULL CHECK (
    jsonb_typeof(requested_times) = 'array'
    AND jsonb_array_length(requested_times) BETWEEN 1 AND 3
  ),
  status TEXT NOT NULL DEFAULT 'requested' CHECK (
    status IN ('requested', 'confirmed', 'declined', 'cancelled')
  ),
  confirmed_for TIMESTAMPTZ,
  confirmed_timezone TEXT,
  confirmed_at TIMESTAMPTZ,
  instructions TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (status <> 'confirmed' OR confirmed_for IS NOT NULL)
);

CREATE TABLE public.property_tour_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id UUID NOT NULL REFERENCES public.property_tour_requests(id) ON DELETE CASCADE,
  sender_type TEXT NOT NULL CHECK (sender_type IN ('guest', 'admin')),
  sender_name TEXT NOT NULL,
  body TEXT NOT NULL CHECK (length(body) BETWEEN 1 AND 3000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.property_tour_email_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invite_id UUID REFERENCES public.property_tour_invites(id) ON DELETE SET NULL,
  request_id UUID REFERENCES public.property_tour_requests(id) ON DELETE SET NULL,
  recipient TEXT NOT NULL,
  email_type TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('sent', 'failed')),
  provider TEXT NOT NULL DEFAULT 'gas',
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX property_tour_requests_status_created_idx
  ON public.property_tour_requests(status, created_at DESC);
CREATE INDEX property_tour_messages_request_created_idx
  ON public.property_tour_messages(request_id, created_at);
CREATE INDEX property_tour_invites_property_created_idx
  ON public.property_tour_invites(property_id, created_at DESC);

ALTER TABLE public.property_tour_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_tour_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_tour_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_tour_email_log ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.property_tour_invites FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.property_tour_requests FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.property_tour_messages FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.property_tour_email_log FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.property_tour_invites TO service_role;
GRANT ALL ON public.property_tour_requests TO service_role;
GRANT ALL ON public.property_tour_messages TO service_role;
GRANT ALL ON public.property_tour_email_log TO service_role;

CREATE OR REPLACE FUNCTION public.property_tours_touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER property_tour_requests_touch_updated_at
  BEFORE UPDATE ON public.property_tour_requests
  FOR EACH ROW EXECUTE FUNCTION public.property_tours_touch_updated_at();